import clsx from 'clsx';
import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';

import './globals.css';
import { Toaster } from '@/components/ui/sonner';

const raleway = Raleway({
  variable: '--font-raleway',
  weight: ['400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Portofolio Yusuf Masdhuki',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={clsx(raleway.variable, 'antialiased')}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
